import { Book } from './types';

export const MOCK_BOOKS: Book[] = [
  {
    id: 1,
    title: "The Shadow of the Wind",
    author: "Carlos Ruiz Zafón",
    cover_url: "https://images.unsplash.com/photo-1543005814-14b24e1fabb0?q=80&w=800&auto=format&fit=crop",
    description: "A young boy explores the Cemetery of Forgotten Books in post-Civil War Barcelona.",
    average_rating: 9.2,
    ratings_count: 1240,
    openlibrary_key: "OL123M",
  },
  {
    id: 2,
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    cover_url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=800&auto=format&fit=crop",
    description: "The life story of Kvothe, a legendary figure in his own time.",
    average_rating: 8.9,
    ratings_count: 3500,
    openlibrary_key: "OL456M",
  },
  {
    id: 3,
    title: "Dune",
    author: "Frank Herbert",
    cover_url: "https://images.unsplash.com/photo-1506466010722-395aa2bef1f5?q=80&w=800&auto=format&fit=crop",
    description: "Political intrigue and giant sand worms on the desert planet Arrakis.",
    average_rating: 9.5,
    ratings_count: 8900,
    openlibrary_key: "OL789M",
  },
  {
    id: 4,
    title: "The Alchemist",
    author: "Paulo Coelho",
    cover_url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=800&auto=format&fit=crop",
    description: "A shepherd boy's journey through North Africa in search of treasure.",
    average_rating: 7.8,
    ratings_count: 15400,
    openlibrary_key: "OL101M",
  },
  {
    id: 5,
    title: "1984",
    author: "George Orwell",
    cover_url: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?q=80&w=800&auto=format&fit=crop",
    description: "A dystopian nightmare of totalitarian surveillance.",
    average_rating: 9.1,
    ratings_count: 12000,
    openlibrary_key: "OL112M",
  },
   {
    id: 6,
    title: "Circe",
    author: "Madeline Miller",
    cover_url: "https://images.unsplash.com/photo-1474932430478-367dbb6832c1?q=80&w=800&auto=format&fit=crop",
    description: "The daughter of Helios carves her own path in the world of gods and mortals.",
    average_rating: 8.7,
    ratings_count: 5600,
    openlibrary_key: "OL131M",
  }
];
